#!/usr/bin/env python
"""Sync Sifty's version across the files that can't read the package metadata.

`src/sifty/__init__.py` (`__version__`) is the single source of truth: the build
(`pyproject.toml`) reads it dynamically, and `sifty version` prints it. A handful
of *other* artifacts hardcode the version because they're not Python and can't
import the package - the website's JSON-LD, the Inno Setup script, the issue
template. This script keeps those in lockstep so a release is one edit, not a
project-wide hunt.

Usage:
    python scripts/bump_version.py X.Y.Z   # set a new version everywhere
    python scripts/bump_version.py          # sync targets to the current __version__
    python scripts/bump_version.py --check  # verify nothing has drifted (exit 1 if it has)

Deliberately NOT touched (they carry download URLs + SHA256 tied to the built
exe, so a blind bump would leave them inconsistent):
  - packaging/winget/*.yaml  -> regenerated by `wingetcreate update ... --version`
  - packaging/scoop/sifty.json -> scoop `autoupdate` recomputes from $version
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The single source of truth. Its match is also used as the version when no
# explicit version is passed on the command line.
SOURCE = ROOT / "src" / "sifty" / "__init__.py"
SOURCE_PATTERN = re.compile(r'(?<=^__version__ = ")[^"]+(?=")', re.MULTILINE)


@dataclass(frozen=True)
class Target:
    """A file that hardcodes the version, plus the regex that isolates it.

    The pattern matches *only* the version substring (via look-around), so the
    current value is ``pattern.search(text).group(0)`` and a bump is a plain
    ``pattern.sub(new_version, text)``.
    """

    path: Path
    pattern: re.Pattern[str]
    label: str


# The source itself is first so an explicit bump rewrites it too.
TARGETS: list[Target] = [
    Target(SOURCE, SOURCE_PATTERN, "package __version__ (source of truth)"),
    Target(
        ROOT / "site" / "index.html",
        re.compile(r'(?<="softwareVersion": ")[^"]+(?=")'),
        "website JSON-LD softwareVersion",
    ),
    Target(
        ROOT / "packaging" / "installer" / "sifty.iss",
        re.compile(r'(?<=#define AppVersion ")[^"]+(?=")'),
        "Inno Setup AppVersion default",
    ),
    Target(
        ROOT / ".github" / "ISSUE_TEMPLATE" / "bug_report.yml",
        re.compile(r"(?<=placeholder: )[0-9][0-9.]*"),
        "issue-template version placeholder",
    ),
]

VERSION_RE = re.compile(r"^\d+\.\d+\.\d+([.-].+)?$")


def _read_current(target: Target) -> str | None:
    """Return the version currently written in *target*, or None if not found."""
    match = target.pattern.search(target.path.read_text(encoding="utf-8"))
    return match.group(0) if match else None


def source_version() -> str:
    """The authoritative version from src/sifty/__init__.py."""
    version = _read_current(TARGETS[0])
    if version is None:
        sys.exit(f"error: no __version__ found in {SOURCE}")
    return version


def cmd_check() -> int:
    """Report any target whose version differs from the source. Exit 1 on drift."""
    want = source_version()
    drifted: list[tuple[Target, str | None]] = []
    for target in TARGETS[1:]:
        have = _read_current(target)
        if have != want:
            drifted.append((target, have))

    if not drifted:
        print(f"OK - all version references match {want}")
        return 0

    print(f"DRIFT - source of truth is {want}, but:")
    for target, have in drifted:
        rel = target.path.relative_to(ROOT)
        shown = have if have is not None else "<not found>"
        print(f"  {shown:>12}  {rel}  ({target.label})")
    print("\nRun `python scripts/bump_version.py` to sync.")
    return 1


def cmd_sync(new_version: str | None) -> int:
    """Write *new_version* (or the current source version) to every target."""
    if new_version is None:
        new_version = source_version()
        targets = TARGETS[1:]  # source already holds it; only sync the rest
    else:
        targets = TARGETS  # explicit bump rewrites the source too

    changed = 0
    for target in targets:
        rel = target.path.relative_to(ROOT)
        text = target.path.read_text(encoding="utf-8")
        if not target.pattern.search(text):
            print(f"  warn: no version reference found in {rel} ({target.label})")
            continue
        updated = target.pattern.sub(new_version, text)
        if updated != text:
            target.path.write_text(updated, encoding="utf-8")
            print(f"  bumped  {rel}  -> {new_version}")
            changed += 1
        else:
            print(f"  ok      {rel}  (already {new_version})")

    print(f"\n{changed} file(s) updated to {new_version}.")
    print("Next: add a CHANGELOG.md section, commit, then tag vX.Y.Z.")
    print(
        "Note: winget + scoop manifests are intentionally left alone - they carry\n"
        "      the exe URL/SHA256 and are handled by wingetcreate / scoop autoupdate."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "version",
        nargs="?",
        help="new version (X.Y.Z). Omit to sync targets to the current __version__.",
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="verify all references match the source; exit 1 on drift.",
    )
    args = parser.parse_args(argv)

    if args.check:
        return cmd_check()
    if args.version is not None and not VERSION_RE.match(args.version):
        sys.exit(f"error: '{args.version}' is not a valid version (expected X.Y.Z)")
    return cmd_sync(args.version)


if __name__ == "__main__":
    raise SystemExit(main())
